version: '3.8'
services:
  db:
    image: mysql:8.4
    container_name: mysql
    restart: always
    env_file:
      - ./apps/web/.env
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
      - ./apps/web/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cofiblocks-network

  prisma:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: prisma
    env_file:
      - ./apps/web/.env
    ports:
      - '5555:5555'
    working_dir: /app
    volumes:
      - ./apps/web/:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "bun prisma generate && bun prisma migrate deploy && bun prisma studio"
    networks:
      - cofiblocks-network

  web:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: web
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    environment:
      - NODE_PATH=/usr/src/app/node_modules
    volumes:
      - ./apps/web/:/usr/src/app/apps/web
      - ./packages/ui:/usr/src/app/packages/ui
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    depends_on:
      - prisma
    networks:
      - cofiblocks-network

  storybook:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./apps/web/.env
    depends_on:
      - prisma
    command: sh -c "bun run dev:storybook"
    networks:
      - cofiblocks-network

volumes:
  mysql-data:

networks:
  cofiblocks-network:
    driver: bridge