// src/server/api/routers/mockProducts.ts

// TODO: Replace this mocked data with real data fetched from the blockchain in the near future.

export const mockedProducts = [
	{
		id: 1,
		tokenId: 1,
		name: "product_name_1",
		price: 15.99,
		region: "Alajuela",
		farmName: "Beneficio Las Peñas",
		strength: "light",
		process: "honey",
		nftMetadata: JSON.stringify({
			description: "product_description_1",
			imageUrl: "/images/cafe1.webp",
			imageAlt: "product_image_alt_1",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 2,
		tokenId: 2,
		name: "product_name_2",
		price: 17.99,
		region: "Cartago",
		farmName: "Beneficio Las Nubes",
		strength: "medium",
		process: "washed",
		nftMetadata: JSON.stringify({
			description: "product_description_2",
			imageUrl: "/images/cafe2.webp",
			imageAlt: "product_image_alt_2",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 3,
		tokenId: 3,
		name: "product_name_3",
		price: 19.99,
		region: "Heredia",
		farmName: "Beneficio Monteverde",
		strength: "strong",
		process: "natural",
		nftMetadata: JSON.stringify({
			description: "product_description_3",
			imageUrl: "/images/cafe3.webp",
			imageAlt: "product_image_alt_3",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 4,
		tokenId: 4,
		name: "product_name_4",
		price: 16.99,
		region: "Guanacaste",
		farmName: "Finca Santa Rosa",
		strength: "light",
		nftMetadata: JSON.stringify({
			description: "product_description_4",
			imageUrl: "/images/cafe4.webp",
			imageAlt: "product_image_alt_4",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 5,
		tokenId: 5,
		name: "product_name_5",
		price: 18.99,
		region: "Puntarenas",
		farmName: "Finca El Mirador",
		strength: "medium",
		nftMetadata: JSON.stringify({
			description: "product_description_5",
			imageUrl: "/images/cafe5.webp",
			imageAlt: "product_image_alt_5",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 6,
		tokenId: 6,
		name: "product_name_6",
		price: 20.99,
		region: "San José",
		farmName: "Finca La Esperanza",
		strength: "extra_strong",
		nftMetadata: JSON.stringify({
			description: "product_description_6",
			imageUrl: "/images/cafe6.webp",
			imageAlt: "product_image_alt_6",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 7,
		tokenId: 7,
		name: "product_name_7",
		price: 14.99,
		region: "Limón",
		farmName: "Finca El Caribe",
		strength: "mild",
		nftMetadata: JSON.stringify({
			description: "product_description_7",
			imageUrl: "/images/cafe7.webp",
			imageAlt: "product_image_alt_7",
		}),
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];
